set( swan_src
${SWAN_GENERATED_SRC}/swan_kinds.f90
${SWAN_GENERATED_SRC}/swan_math_constants.f90
${SWAN_GENERATED_SRC}/swan_io_limits.f90
${SWAN_GENERATED_SRC}/swan_io_units.f90
${SWAN_GENERATED_SRC}/swan_diagnostics_level.f90
${SWAN_GENERATED_SRC}/swan_project_metadata.f90
${SWAN_GENERATED_SRC}/swan_path_separators.f90
${SWAN_GENERATED_SRC}/swan_output_variables.f90
${SWAN_GENERATED_SRC}/swan_output_quadrature.f90
${SWAN_GENERATED_SRC}/swan_output_settings.f90
${SWAN_GENERATED_SRC}/swan_test_output.f90
${SWAN_GENERATED_SRC}/swan_compda_layout.f90
${SWAN_GENERATED_SRC}/swan_spectral_grid.f90
${SWAN_GENERATED_SRC}/swan_computational_grid.f90
${SWAN_GENERATED_SRC}/swan_physical_settings.f90
${SWAN_GENERATED_SRC}/swan_numerics.f90
${SWAN_GENERATED_SRC}/swan_physics_selection.f90
${SWAN_GENERATED_SRC}/swan_stencil.f90
${SWAN_GENERATED_SRC}/swan_propagation_scheme.f90
${SWAN_GENERATED_SRC}/swan_spherical_geometry.f90
${SWAN_GENERATED_SRC}/swan_coordinate_offset.f90
${SWAN_GENERATED_SRC}/swan_computational_grid_kind.f90
${SWAN_GENERATED_SRC}/swan_boundary_counters.f90
${SWAN_GENERATED_SRC}/swan_run_mode.f90
${SWAN_GENERATED_SRC}/swan_input_grids.f90
${SWAN_GENERATED_SRC}/swan_input_field_files.f90
${SWAN_GENERATED_SRC}/swan_parallel_state.f90
${SWAN_GENERATED_SRC}/swan_text_utilities.f90
${SWAN_GENERATED_SRC}/swan_service_interfaces.f90
${SWAN_GENERATED_SRC}/swan_wave_physics.f90
${SWAN_GENERATED_SRC}/swan_grid_point_validation.f90
${SWAN_GENERATED_SRC}/swan_file_opening.f90
${SWAN_GENERATED_SRC}/swan_array_copy.f90
${SWAN_GENERATED_SRC}/swan_spectrum_output.f90
${SWAN_GENERATED_SRC}/swan_coordinate_input.f90
${SWAN_GENERATED_SRC}/swan_angle_conversions.f90
${SWAN_GENERATED_SRC}/swan_number_formatting.f90
${SWAN_GENERATED_SRC}/swan_time.f90
${SWAN_GENERATED_SRC}/swan_spectrum_transform.f90
${SWAN_GENERATED_SRC}/swan_input_point_validation.f90
${SWAN_GENERATED_SRC}/swan_triads.f90
${SWAN_GENERATED_SRC}/swan_field_file_update.f90
${SWAN_GENERATED_SRC}/swan_geometry.f90
${SWAN_GENERATED_SRC}/swan_legacy_io.f90
${SWAN_GENERATED_SRC}/swan_io_context.f90
${SWAN_GENERATED_SRC}/swan_diffraction_state.f90
${SWAN_GENERATED_SRC}/swan_triad_state.f90
${SWAN_GENERATED_SRC}/swan_snl4_tables.f90
${SWAN_GENERATED_SRC}/swan_spectral_powers.f90
${SWAN_GENERATED_SRC}/swan_source_workspaces.f90
${SWAN_GENERATED_SRC}/swmod2.f90
${SWAN_GENERATED_SRC}/swan_output_formats.f90
${SWAN_GENERATED_SRC}/swan_vtk_output.f90
${SWAN_GENERATED_SRC}/swan_input_fields.f90
${SWAN_GENERATED_SRC}/swan_vegetation_layers.f90
${SWAN_GENERATED_SRC}/swan_global_grid.f90
${SWAN_GENERATED_SRC}/SwanSpectPart.f90
${SWAN_GENERATED_SRC}/m_constants.f90
${SWAN_GENERATED_SRC}/m_fileio.f90
${SWAN_GENERATED_SRC}/m_propcache.f90
${SWAN_GENERATED_SRC}/serv_xnl4v5.f90
${SWAN_GENERATED_SRC}/mod_xnl4v5.f90
${SWAN_GENERATED_SRC}/SwanGriddata.f90
${SWAN_GENERATED_SRC}/SwanGridobjects.f90
${SWAN_GENERATED_SRC}/SwanCompdata.f90
${SWAN_GENERATED_SRC}/SdsBabanin.f90
${SWAN_GENERATED_SRC}/SwanIEM.f90
${SWAN_GENERATED_SRC}/SwanBraggScat.f90
${SWAN_GENERATED_SRC}/SwanQCM.f90
${SWAN_GENERATED_SRC}/SwanParallel.f90
${SWAN_GENERATED_SRC}/swanmain.f90
${SWAN_GENERATED_SRC}/swanpre1.f90
${SWAN_GENERATED_SRC}/swanpre2.f90
${SWAN_GENERATED_SRC}/swancom1.f90
${SWAN_GENERATED_SRC}/swancom2.f90
${SWAN_GENERATED_SRC}/swancom3.f90
${SWAN_GENERATED_SRC}/swancom4.f90
${SWAN_GENERATED_SRC}/swancom5.f90
${SWAN_GENERATED_SRC}/swanout1.f90
${SWAN_GENERATED_SRC}/swanout2.f90
${SWAN_GENERATED_SRC}/swanser.f90
${SWAN_GENERATED_SRC}/swanparll.f90
${SWAN_GENERATED_SRC}/SwanReadGrid.f90
${SWAN_GENERATED_SRC}/SwanReadADCGrid.f90
${SWAN_GENERATED_SRC}/SwanReadTriangleGrid.f90
${SWAN_GENERATED_SRC}/SwanReadEasymeshGrid.f90
${SWAN_GENERATED_SRC}/SwanInitCompGrid.f90
${SWAN_GENERATED_SRC}/SwanCheckGrid.f90
${SWAN_GENERATED_SRC}/SwanCreateEdges.f90
${SWAN_GENERATED_SRC}/SwanSpatialIndex.f90
${SWAN_GENERATED_SRC}/SwanGridTopology.f90
${SWAN_GENERATED_SRC}/SwanGridVert.f90
${SWAN_GENERATED_SRC}/SwanGridCell.f90
${SWAN_GENERATED_SRC}/SwanGridFace.f90
${SWAN_GENERATED_SRC}/SwanPrintGridInfo.f90
${SWAN_GENERATED_SRC}/SwanFindPoint.f90
${SWAN_GENERATED_SRC}/SwanPointinMesh.f90
${SWAN_GENERATED_SRC}/SwanBpntlist.f90
${SWAN_GENERATED_SRC}/SwanPrepComp.f90
${SWAN_GENERATED_SRC}/SwanVertlist.f90
${SWAN_GENERATED_SRC}/SwanCompUnstruc.f90
${SWAN_GENERATED_SRC}/SwanDispParm.f90
${SWAN_GENERATED_SRC}/SwanPropvelX.f90
${SWAN_GENERATED_SRC}/SwanSweepSel.f90
${SWAN_GENERATED_SRC}/SwanPropvelS.f90
${SWAN_GENERATED_SRC}/SwanTranspAc.f90
${SWAN_GENERATED_SRC}/SwanTranspX.f90
${SWAN_GENERATED_SRC}/SwanDiffPar.f90
${SWAN_GENERATED_SRC}/SwanGSECorr.f90
${SWAN_GENERATED_SRC}/SwanGradDepthorK.f90
${SWAN_GENERATED_SRC}/SwanGradVel.f90
${SWAN_GENERATED_SRC}/SwanInterpolatePoint.f90
${SWAN_GENERATED_SRC}/swan_input_interpolation.f90
${SWAN_GENERATED_SRC}/SwanInterpolateAc.f90
${SWAN_GENERATED_SRC}/SwanInterpolateOutput.f90
${SWAN_GENERATED_SRC}/swan_structured_output_interpolation.f90
${SWAN_GENERATED_SRC}/SwanConvAccur.f90
${SWAN_GENERATED_SRC}/SwanConvStopc.f90
${SWAN_GENERATED_SRC}/SwanFindObstacles.f90
${SWAN_GENERATED_SRC}/SwanCrossObstacle.f90
${SWAN_GENERATED_SRC}/SwanComputeForce.f90
${SWAN_GENERATED_SRC}/SwanIntgratSpc.f90
${SWAN_GENERATED_SRC}/SwanBndStruc.f90
${SWAN_GENERATED_SRC}/SwanVTKWriteHeader.f90
${SWAN_GENERATED_SRC}/SwanVTKWriteData.f90
${SWAN_GENERATED_SRC}/SwanVTKPDataSets.f90
${SWAN_GENERATED_SRC}/ocpids.f90
${SWAN_GENERATED_SRC}/ocpcre.f90
${SWAN_GENERATED_SRC}/swan_input_helpers.f90
${SWAN_GENERATED_SRC}/fftw_compat.f90
)
