set( swan_src
${SRC}/swan_kinds.f90
${SWAN_GENERATED_SRC}/swan_build_config.f90
${SRC}/swan_math_constants.f90
${SRC}/swan_io_limits.f90
${SRC}/swan_io_units.f90
${SRC}/swan_diagnostics_level.f90
${SRC}/swan_project_metadata.f90
${SRC}/swan_path_separators.f90
${SRC}/swan_output_variables.f90
${SRC}/swan_output_quadrature.f90
${SRC}/swan_output_settings.f90
${SRC}/swan_test_output.f90
${SRC}/swan_compda_layout.f90
${SRC}/swan_spectral_grid.f90
${SRC}/swan_computational_grid.f90
${SRC}/swan_physical_settings.f90
${SRC}/swan_numerics.f90
${SRC}/swan_physics_selection.f90
${SRC}/swan_stencil.f90
${SRC}/swan_propagation_scheme.f90
${SRC}/swan_spherical_geometry.f90
${SRC}/swan_coordinate_offset.f90
${SRC}/swan_computational_grid_kind.f90
${SRC}/swan_boundary_counters.f90
${SRC}/swan_run_mode.f90
${SRC}/swan_input_grids.f90
${SRC}/swan_input_field_files.f90
${SRC}/swan_parallel_state.f90
${SRC}/swan_text_utilities.f90
${SRC}/swan_service_interfaces.f90
${SRC}/swan_wave_physics.f90
${SRC}/swan_grid_point_validation.f90
${SRC}/swan_file_opening.f90
${SRC}/swan_array_copy.f90
${SRC}/swan_spectrum_output.f90
${SRC}/swan_coordinate_input.f90
${SRC}/swan_angle_conversions.f90
${SRC}/swan_number_formatting.f90
${SRC}/swan_time.f90
${SRC}/swan_spectrum_transform.f90
${SRC}/swan_input_point_validation.f90
${SRC}/swan_triads.f90
${SRC}/swan_field_file_update.f90
${SRC}/swan_geometry.f90
${SRC}/swan_legacy_io.f90
${SRC}/swan_io_context.f90
${SRC}/swan_diffraction_state.f90
${SRC}/swan_triad_state.f90
${SRC}/swan_snl4_tables.f90
${SRC}/swan_spectral_powers.f90
${SRC}/swan_source_workspaces.f90
${SRC}/swmod2.f90
${SRC}/swan_output_formats.f90
${SRC}/swan_vtk_output.f90
${SRC}/swan_input_fields.f90
${SRC}/swan_vegetation_layers.f90
${SRC}/swan_global_grid.f90
${SRC}/SwanSpectPart.f90
${SRC}/m_constants.f90
${SRC}/m_fileio.f90
${SRC}/m_propcache.f90
${SRC}/serv_xnl4v5.f90
${SRC}/mod_xnl4v5.f90
${SRC}/SwanGriddata.f90
${SRC}/SwanGridobjects.f90
${SRC}/SwanCompdata.f90
${SRC}/SdsBabanin.f90
${SRC}/SwanIEM.f90
${SRC}/SwanBraggScat.f90
${SRC}/SwanQCM.f90
${SRC}/swan_metis_interface.f90
${SRC}/SwanParallel.f90
${SRC}/swanmain.f90
${SRC}/swan_library.f90
${SRC}/swanpre1.f90
${SRC}/swanpre2.f90
${SRC}/swancom1.f90
${SRC}/swancom2.f90
${SRC}/swancom3.f90
${SRC}/swancom4.f90
${SRC}/swancom5.f90
${SRC}/swanout1.f90
${SRC}/swanout2.f90
${SRC}/swanser.f90
${SRC}/swanparll.f90
${SRC}/SwanReadGrid.f90
${SRC}/SwanReadADCGrid.f90
${SRC}/SwanReadTriangleGrid.f90
${SRC}/SwanReadEasymeshGrid.f90
${SRC}/SwanInitCompGrid.f90
${SRC}/SwanCheckGrid.f90
${SRC}/SwanCreateEdges.f90
${SRC}/SwanSpatialIndex.f90
${SRC}/SwanGridTopology.f90
${SRC}/SwanGridVert.f90
${SRC}/SwanGridCell.f90
${SRC}/SwanGridFace.f90
${SRC}/SwanPrintGridInfo.f90
${SRC}/SwanFindPoint.f90
${SRC}/SwanPointinMesh.f90
${SRC}/SwanBpntlist.f90
${SRC}/SwanPrepComp.f90
${SRC}/SwanVertlist.f90
${SRC}/SwanCompUnstruc.f90
${SRC}/SwanDispParm.f90
${SRC}/SwanPropvelX.f90
${SRC}/SwanSweepSel.f90
${SRC}/SwanPropvelS.f90
${SRC}/SwanTranspAc.f90
${SRC}/SwanTranspX.f90
${SRC}/SwanDiffPar.f90
${SRC}/SwanGSECorr.f90
${SRC}/SwanGradDepthorK.f90
${SRC}/SwanGradVel.f90
${SRC}/SwanInterpolatePoint.f90
${SRC}/swan_input_interpolation.f90
${SRC}/SwanInterpolateAc.f90
${SRC}/SwanInterpolateOutput.f90
${SRC}/swan_structured_output_interpolation.f90
${SRC}/SwanConvAccur.f90
${SRC}/SwanConvStopc.f90
${SRC}/SwanFindObstacles.f90
${SRC}/SwanCrossObstacle.f90
${SRC}/SwanComputeForce.f90
${SRC}/SwanIntgratSpc.f90
${SRC}/SwanBndStruc.f90
${SRC}/SwanVTKWriteHeader.f90
${SRC}/SwanVTKWriteData.f90
${SRC}/SwanVTKPDataSets.f90
${SRC}/ocpids.f90
${SRC}/ocpcre.f90
${SRC}/swan_input_helpers.f90
${SRC}/fftw_compat.f90
)
